### ISSUE TITLE
Give user the possibility to override default settings

### ISSUE THREAD

**Issue by Syntactical01** [nicoespeon/vscode-slides#17]
If possible could you make it so we can overwrite the other theme parameters that your package sets? I love the package but I am trying to change it to a dark theme but I can't because `lineHighlightBackground` is set to `#FFFFFF` and I can't overwrite it.

**Comment by nicoespeon** [comment]
Hi @Syntactical01 👋 

Indeed, the package is very opinionated. The only settings that are configurable so far are the `theme` and the `fontFamily`, because these 2 depend on what's installed on your machine and I wanted it to be flexible.

The settings are defined here: https://github.com/nicoespeon/vscode-slides/blob/master/src/settings.ts

**I don't want to create one option per setting key**, that will be cumbersome to use and maintain. That will also not cover all eventual needs for override.

Here's what I suggest instead: **give the user the possibility to define his own settings instead of the defaults one**. 

This can be achieved by including a special file in the project. 
Let's call that file `.slidesrc`. 
If there's a `.slidesrc` file at the root of the configured `folder`, then it overrides all the computed settings (including `theme` and `fontFamily`).

I won't work on that because I don't need it. But I'm open to review and integrate PRs that would implement it. I can also help and guide the implementation if you have questions.

Would you like to make it happen? 😃  

## Useful links to implement that 

Here's the [contributing guide](https://github.com/nicoespeon/vscode-slides/blob/master/CONTRIBUTING.md).

And here are parts of the code that will certainly be involved:

https://github.com/nicoespeon/vscode-slides/blob/e352316e23f051bf0e5c729e91c8fb42901492ae/src/adapters.ts#L132-L141

https://github.com/nicoespeon/vscode-slides/blob/e352316e23f051bf0e5c729e91c8fb42901492ae/src/domain.ts#L75-L87

**Comment by nicoespeon** [comment]
This has been implemented in version 4.0.0 thanks to @omnoms 🎉 

Check out the CHANGELOG: https://github.com/nicoespeon/vscode-slides/blob/master/CHANGELOG.md#400---2020-04-08
