### ISSUE TITLE
Presentation mode doesn't adhere to workspace settings.json

### ISSUE THREAD

**Issue by omnoms** [nicoespeon/vscode-slides#20]
## Describe the bug

Presentation mode doesn't adhere to the workspace settings for the terminal configuration or just about any custom configuration. If I've set the fontSize to 18 it's loading something entirely different when in presentation mode. Same thing if I set markdown fontSize to 24 it's shown in the normal preview window, but in slides' presentation view, it's not.
If I set workbench.statusBar.visible to true in settings.json, it's not in presentation mode.

## How to reproduce

Configure a custom workspace settings.json file to contrain overrides and more useful and working settings but once you then start with slides in presentation-mode, it's still loading erronous/wrong/default settings.

## Expected behavior

That my workspace settings are actually adhered to when I run in presentation mode.

## Screenshots
Terminal in non-presentation mode
![image](https://user-images.githubusercontent.com/7261863/78132923-d97ddf00-741d-11ea-8dce-60b4f3c484be.png)

Terminal in presentation mode
![image](https://user-images.githubusercontent.com/7261863/78133011-029e6f80-741e-11ea-80af-91b11930d6e2.png)

Markdown in vs code native preview mode
![image](https://user-images.githubusercontent.com/7261863/78133200-4f824600-741e-11ea-813a-8053729c4c02.png)

Markdown in presentation mode
![image](https://user-images.githubusercontent.com/7261863/78133239-6032bc00-741e-11ea-8f91-77d8e6cb1bf7.png)

**Comment by nicoespeon** [comment]
Hi @omnoms and thanks for reporting 👋 

It's the intended behavior. Settings are replaced by the presentation settings when you enter presentation mode, so the editor is actually configured to display the files as slides.

The settings were clearly opinionated at first, so it's simpler for anyone to just start using it.

There are a few settings that can be configured for the extension. But there's no way to override the default settings with custom ones as of today. 

So this is a feature that I'd like to see implemented: https://github.com/nicoespeon/vscode-slides/issues/17

That will basically solve your issue here. I explained how to approach this. If you have some time and are willing to take a stab at it, I'd happily assist and review your PR 👍 
Otherwise, I'll probably tackle it the next time I need to do a presentation with this extension.
