### ISSUE TITLE
command 'slides.toggle' not found

### ISSUE THREAD

**Issue by ayunas** [nicoespeon/vscode-slides#31]
After installing the extension in VScode, when toggling presentation mode, 

error appears : 
```
command slides.toggle not found
```
tried adding this to settings.json with no luck.

![image](https://user-images.githubusercontent.com/30554629/102089836-5b623c80-3de2-11eb-8a6f-b083972bdbf5.png)

**Comment by nicoespeon** [comment]
Hey @ayunas 👋 

That's strange. I just tested on a different computer/VS Code and saw it worked. I will help you understand what's going on.

I have a few questions to dig in:

1. Which OS are you using? Windows? MacOS? Linux?
2. Which version of VS Code are you running on?
3. If you try to launch the slides [from the Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette), does it work?

    ![image](https://user-images.githubusercontent.com/1094774/102358115-21796d80-3f7d-11eb-8842-00fe94c17c57.png)

**Comment by ayunas** [comment]
There were some other extensions in VScode that I removed.  After doing that, your slides extension worked.  

Still confused about the settings though.  Unable to change the font to something else.  

Also, I really like the plugin you made, but one thing that prevents me from using it in my teaching is the fact that I cannot put slides with animations in VScode.  Most of my slides have onClick animations and elements that fade in using powerpoint.  But when I export the slides as .jpegs from ppt to VScode, it loses the animations.  

Any ideas on how to maintain that?  

Keep up the good work :)

**Comment by nicoespeon** [comment]
Maybe there was a conflict with other extensions shortcuts, indeed. It's not clear what was causing this error message 🤔 

**I'm closing the issue** since it seems to be resolved. But I'll continue answering your questions below.

## About settings

> Still confused about the settings though. Unable to change the font to something else.

There is a default style that should work most of the time, but you should be able to override the settings to your needs.

To do so, you can update your default `.vscode/settings.json` when you're **not** in slides mode:

```json
{
  "slides.vscodeSettings": {
    // settings you want to override
  }
}
```

Say you want to change the font for `Helvetica`, you would add the following configuration:

```json
{
  "slides.vscodeSettings": {
    "editor.fontFamily": "Helvetica"
  }
}
```

You can find what are the default settings here: https://github.com/nicoespeon/vscode-slides/blob/master/src/settings.ts

These settings are VS Code ones. The difference is that you'd put these inside `slides.vscodeSettings`.

When you turn the slides mode on, the extension will update VS Code settings in the following order:

1. Using the defaults you can see here: https://github.com/nicoespeon/vscode-slides/blob/master/src/settings.ts
2. Using the values you've set in `slides.vscodeSettings` 

When you turn the slides mode off, the extension will restore your initial settings. That way you can enter and exit a presentation mode.

Is it clearer?

## About animations

As far as I know, there's no "animation" to transition between 2 tabs in VS Code. If you export `.jpg` from PPT, then they won't have the animations indeed. Ideally, you'd need to export a video format like `.gif` or `.mp4`.

I'm not super familiar with recent versions of PPT and never tried that, so I don't know what's possible. Maybe this can help: https://www.youtube.com/watch?v=86TP57vKHe4

Note that even if you manage to get a video out of the slides, it won't react on click. I suspect you need to **time your animations** in PPT so they are translated into a gif. VS Code will then "play" the gif when it's displayed. So the content will "fade in" automatically, but after a specific time instead of the click. 

Another way might be to export each step of an animation as a different image. By going to the next tab, you'll make things appear. There won't be smooth transitions, but if your goal is to progressively display content, that could do it.
