### ISSUE TITLE
Two files .ts next to each other fail to open

### ISSUE THREAD

**Issue by krzkaczor** [nicoespeon/vscode-slides#32]
## Describe the bug

01.md
02.ts
03.ts <-- this will won't open when I switch to presentation mode

**Comment by krzkaczor** [comment]
Okay, sorry it seems like this is not the core of the issue. I can't reproduce it easily right now but later I this week I will prepare a full repro for you.

**Comment by nicoespeon** [comment]
Closing because it's old. But maybe similar to #52 

It seems we are sometimes struggling to properly open all files in the repository. There was no easy way to do so when I implemented this. If there is one now, that code could be revisited: https://github.com/nicoespeon/vscode-slides/blob/4b6161ea8620618ce14f266a944b33d8d70384f7/src/adapters.ts#L34-L49
