### ISSUE TITLE
This plugin seems to have screwed up my editor font size settings.

### ISSUE THREAD

**Issue by geekymon2** [nicoespeon/vscode-slides#39]
_Tell us what you need help with._
Steps to replicate.
1. Install the sliders plugin.
2. enable the plugin by doing ctrl+shift+p
3. uninstall the plugin

Now the enlarged font size is still enabled and i cannot get it back to normal. When i reinstall again and enable it, it goes even bigger. HELP.......... :(

**Comment by geekymon2** [comment]
Nothing seems to be affecting the font size, where is this setting stored? i have removed the Code config, removed the usersettings everything it doesn't go back to normal even tried reinstalling vscode flatpak and seems to be affecting that as well.

**Comment by nicoespeon** [comment]
Hey @geekymon2 👋 

Sorry for the inconvenience. The extension changes VSCode settings on the project where it's activated, then restore the original settings when deactivated.

If you're stuck with the "presentation mode" settings, you can restore it manually. The configuration is stored in a `.vscode/settings.json`, under the project root folder where it was activated. If you delete this file, you'll get your default settings back.

Re-installing VS Code won't change anything since it will continue to pick up the `.vscode/settings.json` file that's present in the project.

Can you check if it's here, delete it and let me know if that worked?

**Comment by geekymon2** [comment]
Thanks, yeah I figured this out later yesterday. And got it sorted. Should those settings be removed by the extension if the extension is uninstalled?

**Comment by nicoespeon** [comment]
> Or alternatively wouldn't it be better to have them in the user settings rather then project settings?

The advantage of doing it "per project" is that it would only impact the project that is being presented. Applying it at the user level would impact all projects, with could be undesired I think.

> Should those settings be removed by the extension if the extension is uninstalled?

That would be a great thing indeed! I didn't think about the scenario of uninstalling the extension. I don't know if an extension _can_ execute some code on uninstall, I'd check this out.

If it can't, I would add an explanation in the README (e.g. some "Known issue" section) to help those who would get into this.

**Comment by geekymon2** [comment]
Great thanks
