### ISSUE TITLE
Ignoring .gif and .webp formats

### ISSUE THREAD

**Issue by mhemrg** [nicoespeon/vscode-slides#52]
I have a few .gif, .webp and .png images between my slides. The extension only opens the .png ones and ignores the rest.

**Comment by nicoespeon** [comment]
Hey @mhemrg 👋 

This is surprising since the extension should open all files, regardless of the extension. I wonder if the problem could be something else, like a race condition…

Are you able to repro this if you only have 3-4 elements? Like a `slides/` folder with 1 .md, 1.png, 1.gif, 1 .webp

I just tried that and it worked. Wondering if that works for you, or if there is something else going on 🤔
